language: node_js
node_js:
  - "0.12"
  - "1.0"
  - "1.8"
sudo: false
script: "grunt testci"
after_success: "grunt coveralls"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4c50a1340755f9cfae72
    on_success: change
    on_failure: always
    on_start: false
