language: node_js
node_js:
  - "node"
sudo: false
script:
  - "npm run ci"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4c50a1340755f9cfae72
    on_success: change
    on_failure: always
    on_start: false
